config/routes.rb
Efgame::Application.routes.draw do

  resources :news

  get "users/ranking"

  resources :round_letters

  resources :game_boards do
    member do
      get :calculate_score
      post :judge
      get :judge
      post :submit
    end
  end

  resources :games do
    resources :chats
  member do
    get :isSubmit
    get :finish_round
    get :wait_for_all_to_submit
  end
  end

resource :profile, only: [:edit] do
  collection do
    patch 'update_password'
  end
end 
 captcha_route

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
  authenticated :user do
    root 'profiles#show', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
end

app/models/game_board.rb
class GameBoard < ActiveRecord::Base
  belongs_to :game
  belongs_to :player, :class_name => "User"
  belongs_to :judge, :class_name => "User"
  validates_uniqueness_of :game_id, :scope => [:player_id], :message => 'قبلا به این بازی پیوسته اید.'
  validates_uniqueness_of :player_id, :message => 'شما به بازی دیگری پیوسته اید'

end

app/controllers/game_boards_controller.rb
class GameBoardsController < ApplicationController
  before_action :set_game_board, only: [:show, :judge, :submit, :edit, :update, :destroy]
  before_action :assign_judge_to_boards, only: :submit
  before_action :set_game, only: :submit

  respond_to :html

  def index
    @game_boards = GameBoard.all
    respond_with(@game_boards)
  end

  def show
    @items = Item.all
    @game_board = GameBoard.find(params[:id])
    @game = @game_board.game
    respond_with(@game_board)
  end

  def new
    @game_board = GameBoard.new

    respond_with(@game_board)

  end

  def edit
  end

  def create
    @game = Game.find(params[:game_id])
    @game_board = @game.game_boards.new()
    @game_board.player = current_user
    @game_board.score = 0
    current_user.game_boards << @game_board
    @started_game_board = GameBoard.where(:game_id => params[:game_id], :player_id => current_user.id).first
    validate_action_create
    @game_started = true if game_is_starting?
    @game_boards = GameBoard.where(:game_id => params[:game_id])

    respond_to do |format|
      if @game_board.save
        format.html { redirect_to @game_board, notice: 'game_board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game_board }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @game_board.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    flash[:notice] = 'GameBoard was successfully updated.' if @game_board.update(game_board_params)
    respond_with(@game_board)
  end
  def submit
    @game_board.update(game_board_params)
    @game.update(done: 1)
    @judge_board = current_user.judge_board
  end
  
  def judge   
    @judge_board = current_user.judge_board
  end
    
  def calculate_score
    @score = 0
    @score = @score + 1 if params[:game_board][:Name] == "1"
    @score = @score + 1 if params[:game_board][:LastName] == "1"
    @score = @score + 1 if params[:game_board][:City] == "1"
    @score = @score + 1 if params[:game_board][:Country] == "1"
    @score = @score + 1 if params[:game_board][:food] == "1"
    @score = @score + 1 if params[:game_board][:animal] == "1"
    @score = @score + 1 if params[:game_board][:object] == "1"
    flash[:notice] = @score
    @game_board = GameBoard.find(params[:id])
    @game_board.update(score: @score + @game_board.score, has_been_judged?: true, judge: nil)
    @game = Game.find(@game_board.game_id)
    
    if @game.game_boards.any? {|i| !i.has_been_judged?}
      @wait = true
    else 
      @wait = false
    end
    
    respond_to do |format|
        format.js
    end
  end
  

  def destroy
    @game_board.destroy
    redirect_to games_path
  end
  
  private
  def assign_judge_to_boards 
    game = Game.find(@game_board.game_id)
    if !game.went_for_judgement
      game.went_for_judgement = true
      game.save
      players = game.players
      judge_players = game.players
      players.each do |player|
        selected_as_judge = judge_players.select{|a| a!=player}.sample
        # logger.warn "selected_as_judge #{selected_as_judge.attributes.inspect}"
        player.game_boards.first.update(judge_id: selected_as_judge.id)
        judge_players = judge_players - [selected_as_judge]
      end   
    end 
  end
    
    def game_is_starting?
      return @game.players.count >= @game.number_of_players
    end
    def game_is_full?
      return @game.players.count > @game.number_of_players
    end
    
    def validate_action_create
      @errors = []
      if game_is_full?
        @errors << 'ظرفیت این بازی تکمیل است'
      end    
    end
    
    def is_final_user?
      return @game.players.count == @game.number_of_players
    end


    def set_game_board
      @game_board = GameBoard.find(params[:id])
    end
    def set_game
      @game = Game.find(@game_board.game_id)
    end

    def game_board_params
      params.require(:game_board).permit(:game_id, :player_id, :judge_id, :Name, :LastName, :City, :Country, :food, :animal, :object)
    end
end

app/helpers/game_boards_helper.rb
module GameBoardsHelper
end

app/views/game_boards/_chats.html.erb
<div id="chatbox">
	<%= form_for [@game, Chat.new], :remote => true do |f| %>
		<%= f.text_area :text %>
		<%= f.submit 'ارسال' %>
	<% end %>
</div>

<% @game.chats.order(:created_at => :desc).each do |chat| %>
    <div class="chat">
      <div class="sender">
        <%= chat.sender.username %>
      </div> 
      <div class="text"><%= chat.text %></div>
	  ------------------------------
    </div>
<% end %>

app/views/game_boards/_form.html.erb
<%= form_for(@game_board) do |f| %>
  <% if @game_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_board.errors.count, "error") %> prohibited this game_board from being saved:</h2>

      <ul>
      <% @game_board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_boards/calculate_score.js.erb
<% if @wait %>
	window.location.href = '<%= wait_for_all_to_submit_game_path(@game) %>';
<% else %>
	<% publish_to "/games/#{@game.id}/show_scores" do %>
		window.location.href = '<%= finish_round_game_path(@game) %>';
	<% end %>
	window.location.href = '<%= finish_round_game_path(@game) %>';
<% end %>

app/views/game_boards/create.js.erb
<% if @errors.any? %> 
  	alert ('<%=raw @errors.first %>');

<% elsif @game_board.errors.any? %>
	alert ('<%=raw @game_board.errors.full_messages %>');

<% elsif @game_started %>
	<% @game_boards.each do |board| %>
		<% publish_to "/#{board.id}/join" do %>
			window.location.href = '<%= game_board_path(board.id) %>'; 
		<% end %>
	<% end %>
			window.location.href = '<%= game_board_path(@started_game_board.id) %>'; 
	
	
	
<% else %>
	$('#players').html('<%= escape_javascript(render :partial => "games/playerstable") %>');
	$('#join-subscriber').html('<%= escape_javascript(render :partial => "layouts/join_subscriber") %>');
	alert('شما با موفقیت به این بازی پیوستید ولی بازی هنوز شروع نشده است.');
<% end %>

<% publish_to "/game_rosters/new" do %>

 	 $("#players").html("<%= escape_javascript(render(:partial => 'games/playerstable' , :object => @game) )%>");
	 $("#new_game_rosters")[0].reset();
	 $("#players").reset();
<% end %>

app/views/game_boards/edit.html.erb
<h1>Editing game_board</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_board %> |
<%= link_to 'Back', game_boards_path %>

app/views/game_boards/index.html.erb
<h1>Listing game_boards</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Player</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_boards.each do |game_board| %>
      <tr>
        <td><%= game_board.game_id %></td>
        <td><%= game_board.player_id %></td>
        <td><%= link_to 'Show', game_board %></td>
        <td><%= link_to 'Edit', edit_game_board_path(game_board) %></td>
        <td><%= link_to 'Destroy', game_board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game roster', new_game_board_path %>

app/views/game_boards/judge.html.erb
<div id="judge" class="game-boards">
<br><br><br>
<h2>شما قضاوت کنید!</h2>
<p> داور شما: <%= @game_board.judge_id %></p>
<p>  بورد شما برای قضاوت: <%= current_user.judge_board.id %></p>


<%= form_for @judge_board, url: {action: "calculate_score"}, html: {method: "get"}, :remote=>true do |f| %>
	<p id="notice"><%= notice %></p>

	<br/>
	<br/>
	<br/>
	<br/>

	<table>
		<thead>
			<td>نام</td>
			<td>نام خانوادگی</td>
			<td>شهر</td>
			<td>کشور</td>
			<td>خوراک</td>
			<td>حیوان</td>
			<td>اشیاء</td>
		</thead>	
		<tr>
			<td><%= @judge_board.Name %>		<%= f.check_box :Name, :disabled => @judge_board.Name=="" %></td>
			<td><%= @judge_board.LastName %>	<%= f.check_box :LastName, :disabled => @judge_board.LastName=="" %></td>
			<td><%= @judge_board.City %>	<%= f.check_box :City, :disabled => @judge_board.City=="" %></td>
			<td><%= @judge_board.Country %>	<%= f.check_box :Country, :disabled => @judge_board.Country=="" %></td>
			<td><%= @judge_board.food %>	<%= f.check_box :food, :disabled => @judge_board.food==""%></td>
			<td><%= @judge_board.animal %>	<%= f.check_box :animal, :disabled => @judge_board.animal=="" %></td>
			<td><%= @judge_board.object %>	<%= f.check_box :object, :disabled => @judge_board.object=="" %></td>
			
		</tr>
	</table>
	<%= f.check_box :judge_id, :style=>"visibility:hidden" %>
	<%= f.submit 'قضاوت', :id=>"Submit" %>
<% end %>	
</div>

<!-- <script src="http://code.jquery.com/jquery-1.9.0.js"></script>
<script>
$(document).ready(function(){
window.setInterval(function() {
		window.location = "/games/<%= @game_board.game_id %>/calculate_score?game_board= <%= @game_board.id %>";
    }, 10000);
    });
</script> -->

app/views/game_boards/new.html.erb
<h1>New game_board</h1>

<%= render 'form' %>

<%= link_to 'Back', game_boards_path %>

app/views/game_boards/show.html.erb
<div class="content-panel">
<%= form_for @game_board, url: {action: "submit"}, html: {method: "post", class: "form-vertical"} do |f| %>
	<p id="notice"><%= notice %></p>



    <!-- this piece of code should be in controller -->
	<% @game = Game.find(@game_board.game_id) %>

		<% @game.round_letters.each do |round| %>
		  <%  if   round.round_number == @game.number_of_rounds  then
				@last_letter = round.letter
			  end
		  %>
		<% end %>

	<div class="col-md-4">
	</div>
	<div class="col-md-4 random_letter">
			<%= @last_letter %>
	</div>
	<div class="col-md-4">
	</div>

	<br/>
	<br/>
	<br/>
	<br/>
	
	<h3><i class="fa fa-angle-right"></i> >> لطفا کلمات مورد نظر خود را در جدول زیر وارد کنید.</h3><hr>
	<table id ="table" class="table table-striped table-advance table-hover">
		<thead>
			<td>نام</td>
			<td>نام خانوادگی</td>
			<td>شهر</td>
			<td>کشور</td>
			<td>خوراک</td>
			<td>حیوان</td>
			<td>اشیاء</td>
		</thead>	
		<tr>
			<td style= "width=50%"><%= f.text_field :Name, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :LastName, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :City, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :Country, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :food, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :animal, :class=>"Class",:style=>"width:90px" %></td>
			<td><%= f.text_field :object, :class=>"Class",:style=>"width:90px" %></td>
		</tr>
	</table>
	<%= f.submit 'استپ', :id=>"Submit", :class=>"btn disabled" %>
	
<% end %>	

<br/>
<h3>گفتگوی دوستانه</h3>

<div id="chats">
 <%= render 'game_boards/chats'%>
</div>
</div>


<script src="http://code.jquery.com/jquery-1.9.0.js"></script>
<script>
$(document).ready(function(){
	
	var toValidate = jQuery('table .Class'), valid = false;
	toValidate.keyup(function () {
    	if (jQuery(this).val().length > 0) {
        	jQuery(this).data('valid', true);
    	} else {
        	jQuery(this).data('valid', false);
    	}
		valid = true;
    	toValidate.each(function () {
        	if (jQuery(this).data('valid') == undefined) {
            	valid = false;
        	} 
			if (jQuery(this).data('valid') == false) {
            	valid = false;
        	} 
    	});
    	if (valid === true) {
        	jQuery("#Submit").removeClass('disabled');
    	} else {
        	jQuery("#Submit").addClass('disabled');
    	}
	});

	window.setInterval(function() {
        $.ajax({
            url: "/games/<%= @game_board.game_id %>/isSubmit",
            context: document.body
            }).done(function(res) {
                if (res=="1"){
                    $("#edit_game_board_<%= @game_board.id %>").submit();
                }
            }); 
    }, 1000);
});

</script> 

app/views/game_boards/submit.html.erb
<br><br><br>
<h2>لطفا منتظر بمانید...</h2>
<script src="http://code.jquery.com/jquery-1.9.0.js"></script>
<script>
$(document).ready(function(){
window.setInterval(function() {
		window.location = "/game_boards/<%= @judge_board.id%>/judge";
    }, 2000);
    });
</script>