config/routes.rb
Efgame::Application.routes.draw do

  resources :news

  get "users/ranking"

  resources :round_letters

  resources :game_boards do
    member do
      get :calculate_score
      post :judge
      get :judge
      post :submit
    end
  end

  resources :games do
    resources :chats
  member do
    get :isSubmit
    get :finish_round
    get :wait_for_all_to_submit
  end
  end

resource :profile, only: [:edit] do
  collection do
    patch 'update_password'
  end
end 
 captcha_route

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
  authenticated :user do
    root 'profiles#show', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to controller: 'profiles', action:'show'  }
        format.json { render 'profiles/show', status: :created, location: @news }
        format.js {}
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html  { redirect_to controller: 'profiles', action:'show'  }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to controller: 'profiles', action:'show'  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content)
    end
end

app/views/news/_form.html.erb
<br><br>
<div class="container jumbotron"style="width:40%; height:70%; direction:rtl">
<%= form_for News.new , :html => {:class => "form-horizontal", :role => "form"} do |f| %>

<div class="">
  
  <%= f.label 'عنوان',:style => "margin-right:150px"%>

    <%= f.text_field :title ,:style => "width:70%;margin-right:150px",:class => "form-control"%>
  
</div>

<div class="">
  
  <%= f.label 'متن' ,:style => "margin-right:150px"%>
    <%= f.text_area :content, :rows => 10  ,:style => "width:70%;margin-right:150px",:class => "form-control" %>
  
</div>
 <br>
  <div style="padding-right:150px">
    <%= content_tag :button, :type => :submit, :class => "btn btn-info btn-medium btn-lg btn-primary btn-purple-color" do %>
    <i class="icon-ok bigger-110" ></i>
    <%=t :submit%>
    <% end %>

    </div>
<% end %>
  <br><br><br>
 </div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>