config/routes.rb
Efgame::Application.routes.draw do

  resources :news

  get "users/ranking"

  resources :round_letters

  resources :game_boards do
    member do
      get :calculate_score
      post :judge
      get :judge
      post :submit
    end
  end

  resources :games do
    resources :chats
  member do
    get :isSubmit
    get :finish_round
    get :wait_for_all_to_submit
  end
  end

resource :profile, only: [:edit] do
  collection do
    patch 'update_password'
  end
end 
 captcha_route

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
  authenticated :user do
    root 'profiles#show', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :creater, :class_name => "User"
  has_many :game_boards, :dependent => :destroy
  has_many :players, through: :game_boards, :source => :player
  has_many :round_letters
  has_many :chats, :dependent => :destroy
  
  scope :not_started, lambda {
    joins(:game_boards).
      select('games.*').
      group('game_boards.game_id').
      having('count(game_boards.game_id) < games.number_of_players')
    }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :finish_round, :wait_for_all_to_submit]
  before_action :authenticate_user!,  :only => [:new, :create, :edit, :update, :destroy]
  respond_to :html

  def index
    @deletegame = Game.where("number_of_rounds <=0 and done=0")
    @deletegame.each { |i| gb = GameBoard.where(game_id: i.id) 
      gb.each{|j| j.destroy
      }
        i.destroy}
    @games = Game.not_started
    respond_with(@games)
  end

  def show

    @players = @game.players
    respond_with(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    @game.creater_id = current_user.id
    if @game.save
      game_board = GameBoard.new(:player_id => current_user.id, :game_id => @game.id)
      game_board.save
    end
    flash[:notice] = 'بازی با موفقیت دخیره شد' if @game.save
    if game_has_started?
      flash[:notice] = 'بازی شروع شده است.'
      redirect_to game_board
    else
      respond_with(@game)
    end
  end



  def update
    @game = Game.find(params[:id])
    flash[:notice] = 'Game was successfully updated.' if @game.update(game_params)
    respond_with(@game)
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end
  def isSubmit   
    @submit = 0
    @users = GameBoard.where(game_id: params[:id])
    @game = Game.find(params[:id])
    @submit = @game.done
    flash[:notice] =@submit
    render :layout => false
  end
  
  def wait_for_all_to_submit
  end
  
  def finish_round
    @boards = @game.game_boards
    @boards.each do |board|
      board.update(has_been_judged?: false, Name: nil, LastName: nil, City: nil, Country: nil, food: nil, animal: nil, object: nil)
    end
    @board_id = current_user.game_boards.first.id
    if(@game.done === 1)
      @game.update(number_of_rounds: @game.number_of_rounds-1 , done: 0, went_for_judgement: 0)
      if @game.number_of_rounds <= 0
        players = @game.players
        players.each do |player|
          player.update(score: player.score + player.game_boards.first.score)
        end
      end
    end
  end
  
  
  private
    
    
    def game_has_started? #shabnam?!!
		@all_letters = ["الف/آ" , "ب" , "پ" , "ت" ,"ث" , "ج" , "چ" , "ح" , "خ" , "د" , "ذ" , "ر"  , "ز" , "ژ" , "س" , "ش" , "ص" , "ض" , "ط" , "ظ" , "ع" , "غ" , "ف" , "ق" , "ک" , "گ" ,   "ل" , "م" , "ن" , "و" , "ه" , "ی" ] 

		for i in 1..@game.number_of_rounds
		  @repetitive=true
		  if  @game.number_of_rounds > 32 then 
			  @random_letter = @all_letters.sample
		  else 
			  while  @repetitive == true  do
				@random_letter = @all_letters.sample
				if @game.round_letters.exists?( :game_id => @game.id , :letter => 
					@random_letter) then
					   @repetitive =true
				else @repetitive =false
				 end
			  end
		  end
			RoundLetter.new_round_letter(@game.id,@random_letter,i)
		end
		
      return @game.players.count >= @game.number_of_players
    end
	
	
    def is_final_user?
      return @game.players.count == @game.number_of_players
    end
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:creater_id, :number_of_rounds, :number_of_players, :players)
    end
end

app/helpers/games_helper.rb
module GamesHelper

end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="form-group">
    <h4>تعداد مراحل</h4>
    <%= f.number_field :number_of_rounds  %>
  </div>
  <div class="form-group">
    <h4>تعداد بازی کنان</h4>
    <%= f.number_field :number_of_players %>
  </div>
  <div class="form-group" >
       <%= f.hidden_field :is_private, :value => params[:is_private] %>
  </div> 
  <br/><br/><br/>
 <div class="actions">
            <%= f.submit "ایجاد بازی", class: "btn btn-theme04 btn-lg" %>
          </div>
<% end %>

app/views/games/_generateLetter.html.erb
 <%= link_to round_letters_path(:game_id => @game, :letter => @random_letter), :method => :post do %>
  harfe jadid
<% end %>

app/views/games/_join.html.erb
<%= link_to game_boards_path(:game_id => @game, :player_id => current_user), :method => :post, :remote => true do %>
    پیوستن به بازی
<% end %>

app/views/games/_playerstable.html.erb
                <table class="responstable">
                  <tbody>

                <tr>
                  <th>شرکت کنندگان</th>

                </tr>
                <% @game.players.each do |player| %>

                    <tr>
                      <td><%= player.username %></td>
                    </tr>
                <% end %>

                </tbody>
              </table>

app/views/games/edit.html.erb
<h1>Editing game</h1>
<header class="special container">
	<span class="icon fa-tablet"></span>
	<h2>نمایش <strong>اطلاعات بازی</strong></h2>
				
</header>
<div class="contain">
<%= render 'form' %>

<%= link_to 'نمایش', @game %> |
<%= link_to 'بازگشت', games_path %>
</div>

app/views/games/finish_round.html.erb
<br><br><br>


        <!-- One -->
<section class="wrapper style2 container special-alt">
  <div class="row 50%">
      <div class="8u 12u(narrower)">

        <header>
            <h2>لیست بازی ها</h2>
        </header>
        <table class="responstable">
          <tbody>

          <tr>
            <th>بازیکن</th>
            <th>امتیاز</th>
          </tr>
          <% @boards.each do |board| %>

              <tr>
                <td><%= board.player.username%></td>
                <td><%= board.score%></td>
              </tr>
          <% end %>

          </tbody>
        </table>
        <br>


      </div>
      <div class="4u 12u(narrower) important(narrower)"> </div>
  </div>
</section>

<script src="http://code.jquery.com/jquery-1.9.0.js"></script>
<script>
$(document).ready(function(){
  destroyflag = 0;
  window.setInterval(function() {
        if(<%= @game.number_of_rounds%> > 0 )
          window.location = "/game_boards/<%= @board_id %>/"; 
        else{

          alert("بازی تمام شده است.");
          window.location ="/games";

        }
    }, 5000);
});

</script>

app/views/games/index.html.erb
<br><br><br>


        <!-- One -->
<div class="col-md-12">
<section class="">
  <div class="row 50%">
      <div class="8u 12u(narrower)">
      
        <div class="content-panel">
                          <h3><i class="fa fa-angle-right"></i> >> لیست بازی ها</h3><hr><table class="table table-striped table-advance table-hover">
                            
                            
                              <thead>
                              <tr>
                                  <th>شماره بازی</th>
                                  <th>ایجاد کننده</th>
                                  <th>تعداد بازکنان</th>
                                  <th>تعداد دورها</th>

                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                              <% @games.each do |game| %>
 								<% if !(game.is_private ) || (current_user && game.creater_id == current_user.id )||(current_user && current_user.is_admin) %>
                                  <tr>
                                    <td><%=link_to game.id, game  %></td>
                                    <td><%= game.creater.username %></td>
                                    <td><%= game.number_of_players %></td>
                                    <td><%= game.number_of_rounds %></td>
                                    <td>

                                    <% if GameBoard.where(:player_id => current_user.id).blank? %>
                                        <%= link_to game_boards_path(:game_id => game, :player_id => current_user), :remote => true, :class=>"btn btn-info  btn-sm",:method => :post do %>پیوستن به بازی<% end %>
                                    <% elsif !(GameBoard.where(:player_id => current_user.id,:game_id => game.id).blank?) %>
                                        <%= link_to 'انصراف از بازی', (GameBoard.where(:player_id => current_user.id,:game_id => game.id).first), method: :delete, data: {:controller => "game_boards",  confirm: 'Are you sure?' } , :class =>"btn btn-danger  btn-sm" %>
                                    <% end %>

                                    </td>
                                  </tr>
                              <% end %>
							  <% end %>
                              </tbody>
                          </table>
      
                      </div>
        
        <br>
        <footer>
          <ul class="buttons">
            <li><%= link_to new_game_path(:is_private => 0 ), :class=>"btn btn-theme02", :style=>"padding:1px 9px;float:right;color:white;margin-left:5px" do %> 
			<h3>بازی عمومی جدید</h3> <% end %></li>   
			<li><%= link_to new_game_path(:is_private => 1 ), :class=>"btn btn-theme02", :style=>"padding:1px 9px;float:right;color:white" do %> 
			<h3>بازی خصوصی جدید</h3> <% end %></li>
          </ul>
        </footer>

      </div>
      <div class="4u 12u(narrower) important(narrower)"> </div>
  </div>
</section>
</div>

app/views/games/isSubmit.html.erb
<%= @submit %>

app/views/games/new.html.erb
    <div class="form-panel">

      <h3><strong>>>بازی جدید</strong></h3>
      <hr>
	  <%= render 'form' %>

	   
    </div>
    

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>


    <header class="special container">
      <span class="icon fa-tablet"></span>
      <h1>نمایش اطلاعات بازی</h1>
        
    </header>
<br><br><br>
<section class="">
   
                <div class="alert alert-danger">
                  <h4>بازی هنوز شروع نشده است.</h4>
                </div>

	                <div id="players">
						<%= render 'playerstable' %>
					</div>
                
<br>
                <footer>
                  <ul class="btn btn-theme04 btn-lg">
                    <li><a href="/games/new" class="button">بازی جدید</a></li>
                  </ul>
                </footer>

                </div>
                  <div class="4u 12u(narrower) important(narrower)">

                

          </section>

<%= subscribe_to "/game_rosters/new" %>

app/views/games/wait_for_all_to_submit.html.erb
<br/><br/><br/>
<h1>لطفا منتظر بمانید تا همه قضاوتشان را تایید کنند</h1>
<%= subscribe_to "/games/#{@game.id}/show_scores" %>